auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: wenin819
url: http://wenin819.com
img_bsurl: http://wenin819.com
feed: /atom.xml
author_info: <a href="http://wenin819.com/">wenin819</a>

encoding: UTF-8
